package P3App;


/**
* P3App/P3.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P3.idl
* Sunday, April 21, 2019 12:08:30 AM CDT
*/

public interface P3 extends P3Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface P3
