package P3App;

/**
* P3App/P3CallBackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P3.idl
* Sunday, April 21, 2019 12:08:30 AM CDT
*/

public final class P3CallBackHolder implements org.omg.CORBA.portable.Streamable
{
  public P3App.P3CallBack value = null;

  public P3CallBackHolder ()
  {
  }

  public P3CallBackHolder (P3App.P3CallBack initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P3App.P3CallBackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    P3App.P3CallBackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P3App.P3CallBackHelper.type ();
  }

}
