package P3App;


/**
* P3App/P3CallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P3.idl
* Sunday, April 21, 2019 12:08:30 AM CDT
*/

public interface P3CallBackOperations 
{
  void inform (String deadline);
  void inform_end ();
  void inform_msg (String msg);
} // interface P3CallBackOperations
