package P3App;


/**
* P3App/P3Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P3.idl
* Sunday, April 21, 2019 12:08:30 AM CDT
*/

public interface P3Operations 
{

  // register
  String reg_account ();

  // Login
  String login_account (String seed, P3App.P3CallBack objref);
  boolean login_bank (String seed);

  // Banker start gambling
  boolean check_before_gamble ();
  boolean start_gamble (String deadline);
  void start_timer (String deadline);

  // Partitioner check if active gambling
  String check_active_gamble ();

  // Partitioner put bet
  String put_bet (String seed, int bet, String hash_value);

  // Verify hash_value
  boolean verify_hash (String seed, String ran_num);
  String player_query_transac ();
  String banker_query_transac (String seed);
} // interface P3Operations
